#!/usr/bin/env python3
"""Batch post-production pipeline for The Muser.

Walks an input directory for WAV files, applies genre-appropriate
post-production, normalizes loudness, exports MP3 at 320 kbps,
adds metadata, and writes a release_manifest.json.

Usage::

    python scripts/post_process_batch.py \\
        --input-dir output/batch_20260228 \\
        --output-dir releases/batch_20260228 \\
        --artist "The Muser" \\
        --album "AI Generated Collection"
"""

import argparse
import json
import logging
import sys
import time
from pathlib import Path

# Ensure project root is on sys.path
PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.audio.postproduction import apply_postproduction, GENRE_PRESETS
from src.audio.export import (
    add_metadata,
    convert_to_mp3,
)
from src.orchestrator.config import TARGET_LUFS

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("muser.postprocess")


def infer_genre_from_path(wav_path: Path) -> str:
    """Try to infer genre from the file path or parent directory name."""
    parts = [p.lower() for p in wav_path.parts]
    for genre in GENRE_PRESETS:
        if genre == "default":
            continue
        if any(genre in part for part in parts):
            return genre
    # Check filename for genre hints
    name = wav_path.stem.lower()
    for genre in GENRE_PRESETS:
        if genre == "default":
            continue
        if genre in name:
            return genre
    return "default"


def title_from_filename(wav_path: Path) -> str:
    """Derive a human-readable title from a filename."""
    stem = wav_path.stem
    # Remove common prefixes
    for prefix in ("candidate_", "gen_", "track_", "best_"):
        if stem.startswith(prefix):
            stem = stem[len(prefix) :]
    return stem.replace("_", " ").replace("-", " ").title()


def process_single(
    wav_path: Path,
    output_dir: Path,
    artist: str,
    album: str,
    genre_override: str | None,
    target_lufs: float,
    skip_existing: bool,
) -> dict | None:
    """Process a single WAV file through the post-production pipeline.

    Returns a manifest entry dict, or None on failure.
    """
    genre = genre_override or infer_genre_from_path(wav_path)
    title = title_from_filename(wav_path)
    stem = wav_path.stem

    mp3_path = output_dir / f"{stem}.mp3"
    if skip_existing and mp3_path.exists():
        logger.info("Skipping (already exists): %s", mp3_path)
        return {
            "source": str(wav_path),
            "mp3": str(mp3_path),
            "genre": genre,
            "title": title,
            "status": "skipped",
        }

    start = time.time()

    try:
        # If input is FLAC, convert to WAV first
        input_path_str = str(wav_path)
        if wav_path.suffix.lower() == ".flac":
            import soundfile as sf

            data, sr = sf.read(input_path_str)
            temp_wav = str(output_dir / f"{stem}_temp.wav")
            sf.write(temp_wav, data, sr)
            input_path_str = temp_wav

        # Step 1: Apply genre-appropriate post-production
        mastered_path = str(output_dir / f"{stem}_mastered.wav")
        apply_postproduction(input_path_str, mastered_path, genre=genre)

        # Step 2: Convert to MP3 at 320 kbps
        convert_to_mp3(mastered_path, str(mp3_path))

        # Step 3: Add metadata
        import datetime

        year = str(datetime.date.today().year)
        comment = "Generated by The Muser (AI music composition system)"

        add_metadata(
            str(mp3_path),
            title=title,
            artist=artist,
            album=album,
            genre=genre.capitalize(),
            year=year,
            comment=comment,
        )

        # Clean up intermediate files
        Path(mastered_path).unlink(missing_ok=True)
        temp_wav_path = output_dir / f"{stem}_temp.wav"
        if temp_wav_path.exists():
            temp_wav_path.unlink(missing_ok=True)

        elapsed = time.time() - start
        logger.info(
            "Processed %s -> %s (genre=%s, %.1fs)",
            wav_path.name,
            mp3_path.name,
            genre,
            elapsed,
        )

        return {
            "source": str(wav_path),
            "mp3": str(mp3_path),
            "genre": genre,
            "title": title,
            "artist": artist,
            "album": album,
            "processing_time_s": round(elapsed, 2),
            "status": "success",
        }

    except Exception as exc:
        logger.error("Failed to process %s: %s", wav_path.name, exc)
        return {
            "source": str(wav_path),
            "genre": genre,
            "title": title,
            "status": "error",
            "error": str(exc),
        }


def main():
    parser = argparse.ArgumentParser(description="Batch post-production for The Muser audio files")
    parser.add_argument(
        "--input-dir",
        required=True,
        help="Directory containing WAV files to process",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Output directory for processed files",
    )
    parser.add_argument(
        "--artist",
        default="The Muser",
        help="Artist name for metadata (default: The Muser)",
    )
    parser.add_argument(
        "--album",
        default="AI Generated Collection",
        help="Album name for metadata",
    )
    parser.add_argument(
        "--genre",
        default=None,
        help="Override genre for all tracks (default: auto-detect from path)",
    )
    parser.add_argument(
        "--target-lufs",
        type=float,
        default=TARGET_LUFS,
        help=f"Target loudness in LUFS (default: {TARGET_LUFS})",
    )
    parser.add_argument(
        "--skip-existing",
        action="store_true",
        help="Skip files that already have an output MP3",
    )

    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir)

    if not input_dir.is_dir():
        logger.error("Input directory not found: %s", input_dir)
        sys.exit(1)

    output_dir.mkdir(parents=True, exist_ok=True)

    # Find all audio files (WAV and FLAC from v1.5)
    wav_files = sorted(input_dir.rglob("*.wav"))
    flac_files = sorted(input_dir.rglob("*.flac"))
    audio_files = wav_files + flac_files
    audio_files.sort(key=lambda p: p.name)

    if not audio_files:
        logger.error("No WAV/FLAC files found in %s", input_dir)
        sys.exit(1)

    logger.info(
        "Found %d audio file(s) in %s (%d WAV, %d FLAC)",
        len(audio_files),
        input_dir,
        len(wav_files),
        len(flac_files),
    )

    # Load generation manifest for alignment scores (if present)
    gen_manifest_path = input_dir / "generation_manifest.json"
    alignment_scores: dict[str, dict] = {}
    if gen_manifest_path.exists():
        try:
            with open(gen_manifest_path) as f:
                gen_manifest = json.load(f)
            for track in gen_manifest.get("tracks", []):
                output_path = track.get("output_path", "")
                if output_path:
                    fname = Path(output_path).name
                    alignment_scores[fname] = {
                        "audio_quality_score": track.get("best_audio_quality_score"),
                        "lyrics_alignment_score": track.get("lyrics_alignment_score"),
                        "text_alignment_score": track.get("text_alignment_score"),
                    }
            logger.info(
                "Loaded alignment scores for %d tracks from generation manifest",
                len(alignment_scores),
            )
        except Exception as exc:
            logger.warning("Failed to load generation manifest: %s", exc)

    manifest_entries: list[dict] = []
    success_count = 0
    error_count = 0

    for i, audio_path in enumerate(audio_files, 1):
        logger.info("[%d/%d] Processing %s", i, len(audio_files), audio_path.name)

        entry = process_single(
            wav_path=audio_path,
            output_dir=output_dir,
            artist=args.artist,
            album=args.album,
            genre_override=args.genre,
            target_lufs=args.target_lufs,
            skip_existing=args.skip_existing,
        )

        if entry:
            # Merge alignment scores from generation manifest
            scores = alignment_scores.get(audio_path.name, {})
            if scores:
                entry.update({k: v for k, v in scores.items() if v is not None})

            manifest_entries.append(entry)
            if entry["status"] == "success":
                success_count += 1
            elif entry["status"] == "error":
                error_count += 1

    # Write release manifest
    manifest_path = output_dir / "release_manifest.json"
    manifest = {
        "artist": args.artist,
        "album": args.album,
        "total_tracks": len(manifest_entries),
        "successful": success_count,
        "errors": error_count,
        "target_lufs": args.target_lufs,
        "tracks": manifest_entries,
    }

    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)

    logger.info(
        "Post-production complete: %d/%d successful, %d errors. Manifest: %s",
        success_count,
        len(audio_files),
        error_count,
        manifest_path,
    )


if __name__ == "__main__":
    main()
